/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/PlanetUpdated.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={materials['Material.038']} />
        <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials['Material.001']} />
        <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={materials['Material.005']} />
        <mesh name="Icosphere004" geometry={nodes.Icosphere004.geometry} material={materials['Material.049']} />
        <mesh name="Icosphere005" geometry={nodes.Icosphere005.geometry} material={materials['Material.047']} />
        <mesh name="Icosphere006" geometry={nodes.Icosphere006.geometry} material={materials['Material.007']} />
        <mesh name="Icosphere007" geometry={nodes.Icosphere007.geometry} material={materials['Material.045']} />
        <mesh name="Icosphere008" geometry={nodes.Icosphere008.geometry} material={materials['Material.060']} />
        <mesh name="Icosphere009" geometry={nodes.Icosphere009.geometry} material={materials['Material.059']} />
        <mesh name="Icosphere010" geometry={nodes.Icosphere010.geometry} material={materials['Material.030']} />
        <mesh name="Icosphere011" geometry={nodes.Icosphere011.geometry} material={materials['Material.032']} />
        <mesh name="Icosphere012" geometry={nodes.Icosphere012.geometry} material={materials['Material.037']} />
        <mesh name="Icosphere013" geometry={nodes.Icosphere013.geometry} material={materials['Material.035']} />
        <mesh name="Icosphere014" geometry={nodes.Icosphere014.geometry} material={materials['Material.021']} />
        <mesh name="Icosphere015" geometry={nodes.Icosphere015.geometry} material={materials['Material.022']} />
        <mesh name="Icosphere016" geometry={nodes.Icosphere016.geometry} material={materials['Material.016']} />
        <mesh name="Icosphere017" geometry={nodes.Icosphere017.geometry} material={materials['Material.015']} />
        <mesh name="Icosphere018" geometry={nodes.Icosphere018.geometry} material={materials['Material.013']} />
        <mesh name="Icosphere019" geometry={nodes.Icosphere019.geometry} material={materials['Material.012']} />
        <mesh name="Icosphere020" geometry={nodes.Icosphere020.geometry} material={materials['Material.009']} />
        <mesh name="Icosphere021" geometry={nodes.Icosphere021.geometry} material={materials['Material.010']} />
        <mesh name="Icosphere022" geometry={nodes.Icosphere022.geometry} material={materials['Material.055']} />
        <mesh name="Icosphere023" geometry={nodes.Icosphere023.geometry} material={materials['Material.050']} />
        <mesh name="Icosphere024" geometry={nodes.Icosphere024.geometry} material={materials['Material.052']} />
        <mesh name="Icosphere025" geometry={nodes.Icosphere025.geometry} material={materials['Material.027']} />
        <mesh name="Icosphere026" geometry={nodes.Icosphere026.geometry} material={materials['Material.024']} />
        <mesh name="Icosphere027" geometry={nodes.Icosphere027.geometry} material={materials['Material.046']} />
        <mesh name="Icosphere028" geometry={nodes.Icosphere028.geometry} material={materials['Material.008']} />
        <mesh name="Icosphere029" geometry={nodes.Icosphere029.geometry} material={materials['Material.061']} />
        <mesh name="Icosphere030" geometry={nodes.Icosphere030.geometry} material={materials['Material.006']} />
        <mesh name="Icosphere031" geometry={nodes.Icosphere031.geometry} material={materials['Material.053']} />
        <mesh name="Icosphere032" geometry={nodes.Icosphere032.geometry} material={materials['Material.051']} />
        <mesh name="Icosphere033" geometry={nodes.Icosphere033.geometry} material={materials['Material.056']} />
        <mesh name="Icosphere034" geometry={nodes.Icosphere034.geometry} material={materials['Material.054']} />
        <mesh name="Icosphere035" geometry={nodes.Icosphere035.geometry} material={materials['Material.058']} />
        <mesh name="Icosphere036" geometry={nodes.Icosphere036.geometry} material={materials['Material.062']} />
        <mesh name="Icosphere037" geometry={nodes.Icosphere037.geometry} material={materials['Material.025']} />
        <mesh name="Icosphere038" geometry={nodes.Icosphere038.geometry} material={materials['Material.029']} />
        <mesh name="Icosphere039" geometry={nodes.Icosphere039.geometry} material={materials['Material.040']} />
        <mesh name="Icosphere040" geometry={nodes.Icosphere040.geometry} material={materials['Material.039']} />
        <mesh name="Icosphere041" geometry={nodes.Icosphere041.geometry} material={materials['Material.041']} />
        <mesh name="Icosphere042" geometry={nodes.Icosphere042.geometry} material={materials['Material.018']} />
        <mesh name="Icosphere043" geometry={nodes.Icosphere043.geometry} material={materials['Material.044']} />
        <mesh name="Icosphere044" geometry={nodes.Icosphere044.geometry} material={materials['Material.011']} />
        <mesh name="Icosphere045" geometry={nodes.Icosphere045.geometry} material={materials['Material.034']} />
        <mesh name="Icosphere046" geometry={nodes.Icosphere046.geometry} material={materials['Material.026']} />
        <mesh name="Icosphere047" geometry={nodes.Icosphere047.geometry} material={materials['Material.014']} />
        <mesh name="Icosphere048" geometry={nodes.Icosphere048.geometry} material={materials['Material.043']} />
        <mesh name="Icosphere049" geometry={nodes.Icosphere049.geometry} material={materials['Material.019']} />
        <mesh name="Icosphere050" geometry={nodes.Icosphere050.geometry} material={materials['Material.023']} />
        <mesh name="Icosphere051" geometry={nodes.Icosphere051.geometry} material={materials['Material.048']} />
        <mesh name="Icosphere052" geometry={nodes.Icosphere052.geometry} material={materials['Material.057']} />
        <mesh name="Icosphere053" geometry={nodes.Icosphere053.geometry} material={materials['Material.033']} />
        <mesh name="Icosphere054" geometry={nodes.Icosphere054.geometry} material={materials['Material.036']} />
        <mesh name="Icosphere055" geometry={nodes.Icosphere055.geometry} material={materials['Material.042']} />
        <mesh name="Icosphere056" geometry={nodes.Icosphere056.geometry} material={materials['Material.020']} />
        <mesh name="Icosphere057" geometry={nodes.Icosphere057.geometry} material={materials['Material.017']} />
        <mesh name="Icosphere058" geometry={nodes.Icosphere058.geometry} material={materials['Material.028']} />
        <mesh name="Icosphere059" geometry={nodes.Icosphere059.geometry} material={materials['Material.031']} />
        <mesh name="Icosphere060" geometry={nodes.Icosphere060.geometry} material={materials['Material.003']} />
        <mesh name="Icosphere061" geometry={nodes.Icosphere061.geometry} material={materials['Material.002']} />
        <mesh name="Icosphere062" geometry={nodes.Icosphere062.geometry} material={materials['Material.004']} />
        <mesh name="Icosphere063" geometry={nodes.Icosphere063.geometry} material={materials['Material.065']} />
        <mesh name="Icosphere064" geometry={nodes.Icosphere064.geometry} material={materials['Material.063']} />
        <mesh name="Icosphere065" geometry={nodes.Icosphere065.geometry} material={materials['Material.066']} />
        <mesh name="Icosphere066" geometry={nodes.Icosphere066.geometry} material={materials['Material.064']} />
        <mesh name="Icosphere067" geometry={nodes.Icosphere067.geometry} material={materials['Material.031']} />
        <mesh name="Icosphere068" geometry={nodes.Icosphere068.geometry} material={materials['Material.067']} />
        <mesh name="Icosphere069" geometry={nodes.Icosphere069.geometry} material={materials['Material.068']} />
        <mesh name="Icosphere070" geometry={nodes.Icosphere070.geometry} material={materials['Material.070']} />
        <mesh name="Icosphere071" geometry={nodes.Icosphere071.geometry} material={materials['Material.069']} />
        <mesh name="Icosphere072" geometry={nodes.Icosphere072.geometry} material={materials['Material.071']} />
        <mesh name="Icosphere073" geometry={nodes.Icosphere073.geometry} material={materials['Material.049']} />
        <mesh name="Icosphere074" geometry={nodes.Icosphere074.geometry} material={materials['Material.047']} />
        <mesh name="Icosphere075" geometry={nodes.Icosphere075.geometry} material={materials['Material.047']} />
        <mesh name="Icosphere076" geometry={nodes.Icosphere076.geometry} material={materials['Material.007']} />
        <mesh name="Icosphere077" geometry={nodes.Icosphere077.geometry} material={materials['Material.007']} />
        <mesh name="Icosphere078" geometry={nodes.Icosphere078.geometry} material={materials['Material.045']} />
        <mesh name="Icosphere079" geometry={nodes.Icosphere079.geometry} material={materials['Material.045']} />
        <mesh name="Icosphere080" geometry={nodes.Icosphere080.geometry} material={materials['Material.060']} />
        <mesh name="Icosphere081" geometry={nodes.Icosphere081.geometry} material={materials['Material.060']} />
        <mesh name="Icosphere082" geometry={nodes.Icosphere082.geometry} material={materials['Material.059']} />
        <mesh name="Icosphere083" geometry={nodes.Icosphere083.geometry} material={materials['Material.059']} />
        <mesh name="Icosphere084" geometry={nodes.Icosphere084.geometry} material={materials['Material.030']} />
        <mesh name="Icosphere085" geometry={nodes.Icosphere085.geometry} material={materials['Material.030']} />
        <mesh name="Icosphere086" geometry={nodes.Icosphere086.geometry} material={materials['Material.032']} />
        <mesh name="Icosphere087" geometry={nodes.Icosphere087.geometry} material={materials['Material.032']} />
        <mesh name="Icosphere088" geometry={nodes.Icosphere088.geometry} material={materials['Material.037']} />
        <mesh name="Icosphere089" geometry={nodes.Icosphere089.geometry} material={materials['Material.037']} />
        <mesh name="Icosphere090" geometry={nodes.Icosphere090.geometry} material={materials['Material.035']} />
        <mesh name="Icosphere091" geometry={nodes.Icosphere091.geometry} material={materials['Material.035']} />
        <mesh name="Icosphere092" geometry={nodes.Icosphere092.geometry} material={materials['Material.021']} />
        <mesh name="Icosphere093" geometry={nodes.Icosphere093.geometry} material={materials['Material.021']} />
        <mesh name="Icosphere094" geometry={nodes.Icosphere094.geometry} material={materials['Material.022']} />
        <mesh name="Icosphere095" geometry={nodes.Icosphere095.geometry} material={materials['Material.022']} />
        <mesh name="Icosphere096" geometry={nodes.Icosphere096.geometry} material={materials['Material.016']} />
        <mesh name="Icosphere097" geometry={nodes.Icosphere097.geometry} material={materials['Material.016']} />
        <mesh name="Icosphere098" geometry={nodes.Icosphere098.geometry} material={materials['Material.015']} />
        <mesh name="Icosphere099" geometry={nodes.Icosphere099.geometry} material={materials['Material.015']} />
        <mesh name="Icosphere100" geometry={nodes.Icosphere100.geometry} material={materials['Material.013']} />
        <mesh name="Icosphere101" geometry={nodes.Icosphere101.geometry} material={materials['Material.013']} />
        <mesh name="Icosphere102" geometry={nodes.Icosphere102.geometry} material={materials['Material.012']} />
        <mesh name="Icosphere103" geometry={nodes.Icosphere103.geometry} material={materials['Material.012']} />
        <mesh name="Icosphere104" geometry={nodes.Icosphere104.geometry} material={materials['Material.009']} />
        <mesh name="Icosphere105" geometry={nodes.Icosphere105.geometry} material={materials['Material.009']} />
        <mesh name="Icosphere106" geometry={nodes.Icosphere106.geometry} material={materials['Material.010']} />
        <mesh name="Icosphere107" geometry={nodes.Icosphere107.geometry} material={materials['Material.010']} />
        <mesh name="Icosphere108" geometry={nodes.Icosphere108.geometry} material={materials['Material.055']} />
        <mesh name="Icosphere109" geometry={nodes.Icosphere109.geometry} material={materials['Material.055']} />
        <mesh name="Icosphere110" geometry={nodes.Icosphere110.geometry} material={materials['Material.050']} />
        <mesh name="Icosphere111" geometry={nodes.Icosphere111.geometry} material={materials['Material.050']} />
        <mesh name="Icosphere112" geometry={nodes.Icosphere112.geometry} material={materials['Material.052']} />
        <mesh name="Icosphere113" geometry={nodes.Icosphere113.geometry} material={materials['Material.052']} />
        <mesh name="Icosphere114" geometry={nodes.Icosphere114.geometry} material={materials['Material.027']} />
        <mesh name="Icosphere115" geometry={nodes.Icosphere115.geometry} material={materials['Material.027']} />
        <mesh name="Icosphere116" geometry={nodes.Icosphere116.geometry} material={materials['Material.024']} />
        <mesh name="Icosphere117" geometry={nodes.Icosphere117.geometry} material={materials['Material.024']} />
        <mesh name="Icosphere118" geometry={nodes.Icosphere118.geometry} material={materials['Material.046']} />
        <mesh name="Icosphere119" geometry={nodes.Icosphere119.geometry} material={materials['Material.008']} />
        <mesh name="Icosphere120" geometry={nodes.Icosphere120.geometry} material={materials['Material.061']} />
        <mesh name="Icosphere121" geometry={nodes.Icosphere121.geometry} material={materials['Material.006']} />
        <mesh name="Icosphere122" geometry={nodes.Icosphere122.geometry} material={materials['Material.053']} />
        <mesh name="Icosphere123" geometry={nodes.Icosphere123.geometry} material={materials['Material.051']} />
        <mesh name="Icosphere124" geometry={nodes.Icosphere124.geometry} material={materials['Material.056']} />
        <mesh name="Icosphere125" geometry={nodes.Icosphere125.geometry} material={materials['Material.054']} />
        <mesh name="Icosphere126" geometry={nodes.Icosphere126.geometry} material={materials['Material.058']} />
        <mesh name="Icosphere127" geometry={nodes.Icosphere127.geometry} material={materials['Material.062']} />
        <mesh name="Icosphere128" geometry={nodes.Icosphere128.geometry} material={materials['Material.025']} />
        <mesh name="Icosphere129" geometry={nodes.Icosphere129.geometry} material={materials['Material.029']} />
        <mesh name="Icosphere130" geometry={nodes.Icosphere130.geometry} material={materials['Material.040']} />
        <mesh name="Icosphere131" geometry={nodes.Icosphere131.geometry} material={materials['Material.039']} />
        <mesh name="Icosphere132" geometry={nodes.Icosphere132.geometry} material={materials['Material.041']} />
        <mesh name="Icosphere133" geometry={nodes.Icosphere133.geometry} material={materials['Material.018']} />
        <mesh name="Icosphere134" geometry={nodes.Icosphere134.geometry} material={materials['Material.044']} />
        <mesh name="Icosphere135" geometry={nodes.Icosphere135.geometry} material={materials['Material.011']} />
        <mesh name="Icosphere136" geometry={nodes.Icosphere136.geometry} material={materials['Material.034']} />
        <mesh name="Icosphere137" geometry={nodes.Icosphere137.geometry} material={materials['Material.026']} />
        <mesh name="Icosphere138" geometry={nodes.Icosphere138.geometry} material={materials['Material.014']} />
        <mesh name="Icosphere139" geometry={nodes.Icosphere139.geometry} material={materials['Material.043']} />
        <mesh name="Icosphere140" geometry={nodes.Icosphere140.geometry} material={materials['Material.043']} />
        <mesh name="Icosphere141" geometry={nodes.Icosphere141.geometry} material={materials['Material.019']} />
        <mesh name="Icosphere142" geometry={nodes.Icosphere142.geometry} material={materials['Material.019']} />
        <mesh name="Icosphere143" geometry={nodes.Icosphere143.geometry} material={materials['Material.023']} />
        <mesh name="Icosphere144" geometry={nodes.Icosphere144.geometry} material={materials['Material.023']} />
        <mesh name="Icosphere145" geometry={nodes.Icosphere145.geometry} material={materials['Material.048']} />
        <mesh name="Icosphere146" geometry={nodes.Icosphere146.geometry} material={materials['Material.048']} />
        <mesh name="Icosphere147" geometry={nodes.Icosphere147.geometry} material={materials['Material.057']} />
        <mesh name="Icosphere148" geometry={nodes.Icosphere148.geometry} material={materials['Material.057']} />
        <mesh name="Icosphere149" geometry={nodes.Icosphere149.geometry} material={materials['Material.033']} />
        <mesh name="Icosphere150" geometry={nodes.Icosphere150.geometry} material={materials['Material.033']} />
        <mesh name="Icosphere151" geometry={nodes.Icosphere151.geometry} material={materials['Material.036']} />
        <mesh name="Icosphere152" geometry={nodes.Icosphere152.geometry} material={materials['Material.036']} />
        <mesh name="Icosphere153" geometry={nodes.Icosphere153.geometry} material={materials['Material.042']} />
        <mesh name="Icosphere154" geometry={nodes.Icosphere154.geometry} material={materials['Material.020']} />
        <mesh name="Icosphere155" geometry={nodes.Icosphere155.geometry} material={materials['Material.017']} />
        <mesh name="Icosphere156" geometry={nodes.Icosphere156.geometry} material={materials['Material.028']} />
        <mesh name="Icosphere157" geometry={nodes.Icosphere157.geometry} material={materials['Material.003']} />
        <mesh name="Icosphere158" geometry={nodes.Icosphere158.geometry} material={materials['Material.004']} />
        <mesh name="Icosphere159" geometry={nodes.Icosphere159.geometry} material={materials['Material.004']} />
        <mesh name="Icosphere160" geometry={nodes.Icosphere160.geometry} material={materials['Material.004']} />
        <mesh name="Icosphere161" geometry={nodes.Icosphere161.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/PlanetUpdated.glb')
